In [2]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [7]:
np.median([1,2,3])

np.float64(2.0)

In [15]:
np.sum([1,2,3])


np.int64(6)

In [6]:
np.mean([1,2,3])

np.float64(2.0)

In [8]:
np.median([1,2,3])

np.float64(2.0)

In [9]:
np.max([1,2,3])

np.int64(3)

In [10]:
np.min([1,2,3])

np.int64(1)

In [11]:
np.sqrt([1,4,9])

array([1., 2., 3.])

In [12]:
np.power([1,2,3],2)

array([1, 4, 9])

In [13]:
np.sort([3,1,2])

array([1, 2, 3])

In [14]:
np.append([1,2,3], 4)

array([1, 2, 3, 4])

In [16]:
np.split(np.array([1,2,3,4]), 2)

[array([1, 2]), array([3, 4])]

In [17]:
np.size([1,2,3,4])

4

In [19]:
np.unique([1,2,2,3])

array([1, 2, 3])

In [20]:
np.insert([1,2,3],1,10)

array([ 1, 10,  2,  3])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [26]:
np.random.rand(2,2)

array([[0.8047709 , 0.79377139],
       [0.39152672, 0.55686283]])

In [27]:
np.random.randint(1,10,(2,2))

array([[4, 4],
       [5, 3]])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.empty((2,2))

array([[0.8047709 , 0.79377139],
       [0.39152672, 0.55686283]])

In [31]:
np.array([])

array([], dtype=float64)

In [32]:
np.reshape([1,2,3,4], (2,2))

array([[1, 2],
       [3, 4]])

In [33]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [34]:
np.transpose([[1,2],[3,4]])

array([[1, 3],
       [2, 4]])

In [35]:
np.delete([1,2,3,4], 1)

array([1, 3, 4])

In [36]:
np.concatenate(([1,2],[3,4]))

array([1, 2, 3, 4])

In [37]:
np.vstack(([1,2],[3,4]))


array([[1, 2],
       [3, 4]])

In [38]:
np.hstack(([1,2],[3,4]))

array([1, 2, 3, 4])

In [39]:
np.array([[1,2],[3,4]]).shape

(2, 2)

In [40]:
np.array([1,2,3]).dtype

dtype('int64')